// DO NOT EDIT: This file is generated from schema.org data.
import type { ClassArticle } from "./Article.ts";

/** A Report generated by governmental or non-governmental organization. */
export interface ClassReport extends ClassArticle {
  /** The number or other unique designator assigned to a Report by the publishing organization. */
  reportNumber: Array<string>;
}
