// DO NOT EDIT: This file is generated.
import type { SchemaOrg_Article } from "./SchemaOrg_Article.ts";
import type { SchemaOrg_Text } from "./SchemaOrg_Text.ts";

/**
 * A Report generated by governmental or non-governmental organization.
 * @see https://schema.org/Report
 */
export const SCHEMA_ORG_Report = "https://schema.org/Report" as const;

/**
 * A Report generated by governmental or non-governmental organization.
 * @see https://schema.org/Report
 */
export interface SchemaOrg_Report extends SchemaOrg_Article {
    /**
     * The number or other unique designator assigned to a Report by the publishing organization.
     * @see https://schema.org/reportNumber
     */
    reportNumber?: Array<SchemaOrg_Text>;
}
