// DO NOT EDIT: This file is generated from schema.org data.
import type { ClassIntangible } from "./Intangible.ts";

/** A service provided by an organization, e.g. delivery service, print services, etc. */
export interface ClassService extends ClassIntangible {
  /** The overall rating, based on a collection of reviews or ratings, of the item. */
  aggregateRating: Array<{ "@id": string }>;
  /** The geographic area where a service or offered item is provided. */
  areaServed: Array<string | { "@id": string }>;
  /** An intended audience, i.e. a group for whom something was created. */
  audience: Array<{ "@id": string }>;
  /** A means of accessing the service (e.g. a phone bank, a web site, a location, etc.). */
  availableChannel: Array<{ "@id": string }>;
  /** An award won by or for this item. */
  award: Array<string>;
  /** The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person. */
  brand: Array<{ "@id": string }>;
  /** An entity that arranges for an exchange between a buyer and a seller.  In most cases a broker never acquires or releases ownership of a product or service involved in an exchange.  If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred. */
  broker: Array<{ "@id": string }>;
  /** A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy. */
  category: Array<string | { "@id": string }>;
  /** Certification information about a product, organization, service, place, or person. */
  hasCertification: Array<{ "@id": string }>;
  /** Indicates an OfferCatalog listing for this Organization, Person, or Service. */
  hasOfferCatalog: Array<{ "@id": string }>;
  /** The hours during which this service or contact is available. */
  hoursAvailable: Array<{ "@id": string }>;
  /** A pointer to another, somehow related product (or multiple products). */
  isRelatedTo: Array<{ "@id": string }>;
  /** A pointer to another, functionally similar product (or multiple products). */
  isSimilarTo: Array<{ "@id": string }>;
  /** An associated logo. */
  logo: Array<{ "@id": string }>;
  /**
   * An offer to provide this item&#x2014;for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use [[businessFunction]] to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a [[Demand]]. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.
   */
  offers: Array<{ "@id": string }>;
  /** The tangible thing generated by the service, e.g. a passport, permit, etc. */
  produces: Array<{ "@id": string }>;
  /** The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller. */
  provider: Array<{ "@id": string }>;
  /** Indicates the mobility of a provided service (e.g. 'static', 'dynamic'). */
  providerMobility: Array<string>;
  /** A review of the item. */
  review: Array<{ "@id": string }>;
  /** The geographic area where the service is provided. */
  serviceArea: Array<{ "@id": string }>;
  /** The audience eligible for this service. */
  serviceAudience: Array<{ "@id": string }>;
  /** The tangible thing generated by the service, e.g. a passport, permit, etc. */
  serviceOutput: Array<{ "@id": string }>;
  /** The type of service being offered, e.g. veterans' benefits, emergency relief, etc. */
  serviceType: Array<string | { "@id": string }>;
  /** A slogan or motto associated with the item. */
  slogan: Array<string>;
  /** Human-readable terms of service documentation. */
  termsOfService: Array<string | { "@id": string }>;
}
